/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/conversations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Conversation */
        readonly post: operations["create_conversation_api_v1_conversations_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/{conversation_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Conversation */
        readonly get: operations["get_conversation_api_v1_conversations__conversation_id__get"];
        readonly put?: never;
        readonly post?: never;
        /** Reset Conversation */
        readonly delete: operations["reset_conversation_api_v1_conversations__conversation_id__delete"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/{conversation_id}/messages": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Send Message */
        readonly post: operations["send_message_api_v1_conversations__conversation_id__messages_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/{conversation_id}/profile": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /** Patch Profile */
        readonly patch: operations["patch_profile_api_v1_conversations__conversation_id__profile_patch"];
        readonly trace?: never;
    };
    readonly "/api/v1/conversations/{conversation_id}/recommendations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Recommendations */
        readonly get: operations["get_recommendations_api_v1_conversations__conversation_id__recommendations_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Health */
        readonly get: operations["health_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConstraintStrength
         * @enum {string}
         */
        readonly ConstraintStrength: "HARD" | "PREFERENCE" | "UNSET";
        /**
         * ConversationStage
         * @enum {string}
         */
        readonly ConversationStage: "NEW" | "DISCOVERING" | "RESOLVING_CONFLICT" | "READY_TO_MATCH" | "MATCHING" | "RECOMMENDED" | "NOT_RECOMMENDED" | "COMPLETED" | "EXPIRED" | "RESET";
        /**
         * CostLevel
         * @enum {string}
         */
        readonly CostLevel: "LOW" | "MEDIUM" | "MEDIUM_HIGH" | "HIGH";
        /** CreateConversationData */
        readonly CreateConversationData: {
            readonly assistantMessage: components["schemas"]["PublicMessage"];
            readonly conversation: components["schemas"]["PublicConversationSummary"];
            readonly nextQuestion: components["schemas"]["PublicQuestion"];
        };
        /** CreateConversationRequest */
        readonly CreateConversationRequest: {
            /**
             * Clientlocale
             * @default zh-CN
             * @constant
             */
            readonly clientLocale: "zh-CN";
        };
        /** CreateConversationResponse */
        readonly CreateConversationResponse: {
            readonly data: components["schemas"]["CreateConversationData"];
            readonly meta: components["schemas"]["ResponseMeta"];
        };
        /**
         * DataNature
         * @enum {string}
         */
        readonly DataNature: "DEMO_SIMULATED";
        /**
         * DirectionKind
         * @enum {string}
         */
        readonly DirectionKind: "BREED" | "TYPE";
        /** GetConversationData */
        readonly GetConversationData: {
            readonly conversation: components["schemas"]["PublicConversationSummary"];
            readonly currentQuestion: components["schemas"]["PublicQuestion"] | null;
            /** Messages */
            readonly messages: readonly components["schemas"]["PublicMessage"][];
            readonly recommendation: components["schemas"]["PublicRecommendation"] | null;
        };
        /** GetConversationResponse */
        readonly GetConversationResponse: {
            readonly data: components["schemas"]["GetConversationData"];
            readonly meta: components["schemas"]["ResponseMeta"];
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * ListingStatus
         * @enum {string}
         */
        readonly ListingStatus: "SIMULATED_AVAILABLE";
        /**
         * MatchLevel
         * @enum {string}
         */
        readonly MatchLevel: "HIGH" | "MEDIUM" | "CAUTION";
        /** PatchProfileRequest */
        readonly PatchProfileRequest: {
            /** Baserevision */
            readonly baseRevision: number;
            /** Updates */
            readonly updates: {
                readonly [key: string]: components["schemas"]["ProfileUpdate"];
            };
        };
        /** ProfileUpdate */
        readonly ProfileUpdate: {
            /** @default PREFERENCE */
            readonly constraintStrength: components["schemas"]["ConstraintStrength"];
            readonly value: components["schemas"]["PublicProfileValue"];
        };
        /** PublicContactAction */
        readonly PublicContactAction: {
            /**
             * Available
             * @default false
             */
            readonly available: boolean;
            /**
             * Label
             * @default 联系商家进一步了解
             */
            readonly label: string;
            /**
             * Type
             * @default DEMO_CONTACT_MERCHANT
             */
            readonly type: string;
            /**
             * Unavailablemessage
             * @default Demo演示功能，暂未开放。
             */
            readonly unavailableMessage: string;
        };
        /** PublicConversationSummary */
        readonly PublicConversationSummary: {
            /** Activeblockers */
            readonly activeBlockers: readonly string[];
            /** Conflicts */
            readonly conflicts: readonly string[];
            /** Conversationid */
            readonly conversationId: string;
            /**
             * Expiresat
             * Format: date-time
             */
            readonly expiresAt: string;
            /**
             * Lastactiveat
             * Format: date-time
             */
            readonly lastActiveAt: string;
            /** Missingcriticalslots */
            readonly missingCriticalSlots: readonly string[];
            /** Profilesummary */
            readonly profileSummary: {
                readonly [key: string]: components["schemas"]["PublicSlotSummary"];
            };
            readonly recommendationMode: components["schemas"]["RecommendationMode"];
            /** Revision */
            readonly revision: number;
            readonly stage: components["schemas"]["ConversationStage"];
        };
        /** PublicDirectionResult */
        readonly PublicDirectionResult: {
            readonly acquisitionCostLevel: components["schemas"]["CostLevel"];
            /** Directionid */
            readonly directionId: string;
            /**
             * Evidence
             * @default []
             */
            readonly evidence: readonly components["schemas"]["PublicEvidence"][];
            /** Evidencenote */
            readonly evidenceNote: string;
            readonly kind: components["schemas"]["DirectionKind"];
            readonly matchLevel: components["schemas"]["MatchLevel"];
            /** Mismatchpoints */
            readonly mismatchPoints: readonly string[];
            /** Name */
            readonly name: string;
            readonly ongoingCareCostLevel: components["schemas"]["CostLevel"];
            /** Pendingitems */
            readonly pendingItems: readonly string[];
            /** Sourceids */
            readonly sourceIds: readonly string[];
            /** Suitablereasons */
            readonly suitableReasons: readonly string[];
            /** Tradeoffs */
            readonly tradeoffs: readonly string[];
        };
        /** PublicErrorBody */
        readonly PublicErrorBody: {
            /** Code */
            readonly code: string;
            /** Details */
            readonly details: {
                readonly [key: string]: unknown;
            };
            /** Message */
            readonly message: string;
            /** Retryable */
            readonly retryable: boolean;
        };
        /** PublicErrorResponse */
        readonly PublicErrorResponse: {
            readonly error: components["schemas"]["PublicErrorBody"];
            readonly meta: components["schemas"]["ResponseMeta"];
        };
        /** PublicEvidence */
        readonly PublicEvidence: {
            /** Sourceid */
            readonly sourceId: string;
            /** Sourcelocator */
            readonly sourceLocator: string;
            /** Sourcename */
            readonly sourceName: string;
        };
        /** PublicMerchantResult */
        readonly PublicMerchantResult: {
            /** Displayname */
            readonly displayName: string;
            /**
             * Issimulated
             * @default true
             */
            readonly isSimulated: boolean;
            /** Merchantid */
            readonly merchantId: string;
        };
        /** PublicMessage */
        readonly PublicMessage: {
            /** Content */
            readonly content: string;
            /**
             * Createdat
             * Format: date-time
             */
            readonly createdAt: string;
            /** Messageid */
            readonly messageId: string;
            /**
             * Role
             * @enum {string}
             */
            readonly role: "USER" | "ASSISTANT";
        };
        /** PublicPetResult */
        readonly PublicPetResult: {
            readonly acquisitionCostLevel: components["schemas"]["CostLevel"];
            readonly contactAction: components["schemas"]["PublicContactAction"];
            readonly dataNature: components["schemas"]["DataNature"];
            /** Directionid */
            readonly directionId: string;
            /**
             * Evidence
             * @default []
             */
            readonly evidence: readonly components["schemas"]["PublicEvidence"][];
            /** Knownnotes */
            readonly knownNotes: readonly string[];
            /** Listingdisclosure */
            readonly listingDisclosure: string;
            readonly listingStatus: components["schemas"]["ListingStatus"];
            readonly matchLevel: components["schemas"]["MatchLevel"];
            readonly merchant: components["schemas"]["PublicMerchantResult"];
            /** Mismatchpoints */
            readonly mismatchPoints: readonly string[];
            /** Nickname */
            readonly nickname: string;
            readonly ongoingCareCostLevel: components["schemas"]["CostLevel"];
            /** Pendingitems */
            readonly pendingItems: readonly string[];
            /** Petid */
            readonly petId: string;
            /** Sourceids */
            readonly sourceIds: readonly string[];
            /** Suitablereasons */
            readonly suitableReasons: readonly string[];
            /** Tradeoffs */
            readonly tradeoffs: readonly string[];
            /** Unknownfields */
            readonly unknownFields: readonly string[];
        };
        /** PublicProfileChange */
        readonly PublicProfileChange: {
            readonly previousValue?: components["schemas"]["PublicProfileValue"] | null;
            readonly slotName: components["schemas"]["PublicProfileSlotName"];
            readonly status: components["schemas"]["SlotStatus"];
            readonly value?: components["schemas"]["PublicProfileValue"] | null;
        };
        /** @enum {string} */
        readonly PublicProfileSlotName: "speciesScope" | "directionAndSizePreference" | "agePreference" | "coatAppearancePreference" | "interactionRhythm" | "companionshipDistance" | "currentTimeArrangement" | "ongoingInvestmentWillingness" | "disturbanceTolerance" | "allergySpecies" | "absoluteBottomLines" | "acceptedAdjustments" | "priorityNotes" | "volunteeredContext";
        readonly PublicProfileValue: string | number | boolean | readonly string[];
        /** PublicQuestion */
        readonly PublicQuestion: {
            /** Questionid */
            readonly questionId: string;
            /** Quickreplies */
            readonly quickReplies: readonly string[];
            /** Text */
            readonly text: string;
        };
        /** PublicRecommendation */
        readonly PublicRecommendation: {
            /** Directions */
            readonly directions: readonly components["schemas"]["PublicDirectionResult"][];
            /**
             * Disclaimer
             * @default 咕噜港负责匹配并帮助联系商家进一步了解，不直接销售宠物。
             */
            readonly disclaimer: string;
            /**
             * Generalrisks
             * @default [
             *       "品种或类型只表示群体倾向，具体个体仍需继续了解",
             *       "平台不对宠物健康、性格或持续在售作绝对保证"
             *     ]
             */
            readonly generalRisks: readonly string[];
            /** Petavailabilitynote */
            readonly petAvailabilityNote?: string | null;
            /** Pets */
            readonly pets: readonly components["schemas"]["PublicPetResult"][];
            /** Prioritymessage */
            readonly priorityMessage?: string | null;
        };
        /** PublicRecommendationChange */
        readonly PublicRecommendationChange: {
            /**
             * Changetype
             * @enum {string}
             */
            readonly changeType: "ADDED" | "REMOVED" | "LEVEL_CHANGED" | "STATUS_CHANGED" | "UNCHANGED";
            /** Detail */
            readonly detail: string;
            /** Subjectid */
            readonly subjectId?: string | null;
        };
        /** PublicSlotSummary */
        readonly PublicSlotSummary: {
            readonly status: components["schemas"]["SlotStatus"];
            /** Value */
            readonly value?: string | number | boolean | readonly string[] | null;
        };
        /** RecommendationData */
        readonly RecommendationData: {
            readonly conversation: components["schemas"]["PublicConversationSummary"];
            readonly recommendation: components["schemas"]["PublicRecommendation"];
        };
        /**
         * RecommendationMode
         * @enum {string}
         */
        readonly RecommendationMode: "NONE" | "PROVISIONAL" | "FINAL";
        /** RecommendationResponse */
        readonly RecommendationResponse: {
            readonly data: components["schemas"]["RecommendationData"];
            readonly meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseMeta */
        readonly ResponseMeta: {
            /** Requestid */
            readonly requestId: string;
        };
        /** SendMessageRequest */
        readonly SendMessageRequest: {
            /** Baserevision */
            readonly baseRevision: number;
            /** Clientmessageid */
            readonly clientMessageId: string;
            /** Content */
            readonly content: string;
            /** Quickreplyid */
            readonly quickReplyId?: string | null;
        };
        /**
         * SlotStatus
         * @enum {string}
         */
        readonly SlotStatus: "UNKNOWN" | "INFERRED" | "CONFIRMED" | "DECLINED" | "CONFLICTED";
        /** TurnData */
        readonly TurnData: {
            readonly assistantMessage: components["schemas"]["PublicMessage"];
            readonly conversation: components["schemas"]["PublicConversationSummary"];
            readonly nextQuestion: components["schemas"]["PublicQuestion"] | null;
            /** Profilechanges */
            readonly profileChanges: readonly components["schemas"]["PublicProfileChange"][];
            /** Quickreplies */
            readonly quickReplies: readonly string[];
            readonly recommendation: components["schemas"]["PublicRecommendation"] | null;
            /**
             * Recommendationchanges
             * @default []
             */
            readonly recommendationChanges: readonly components["schemas"]["PublicRecommendationChange"][];
            /** Warnings */
            readonly warnings: readonly string[];
        };
        /** TurnResponse */
        readonly TurnResponse: {
            readonly data: components["schemas"]["TurnData"];
            readonly meta: components["schemas"]["ResponseMeta"];
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly create_conversation_api_v1_conversations_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CreateConversationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_conversation_api_v1_conversations__conversation_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GetConversationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly reset_conversation_api_v1_conversations__conversation_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话不存在或已经重置 */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PublicErrorResponse"];
                };
            };
            /** @description 会话已经过期 */
            readonly 410: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PublicErrorResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly send_message_api_v1_conversations__conversation_id__messages_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly patch_profile_api_v1_conversations__conversation_id__profile_patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PatchProfileRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_recommendations_api_v1_conversations__conversation_id__recommendations_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly conversation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly health_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
}
